language: ruby

rvm:
  - 2.3.4
  - 2.2.7
  - 2.1.10

before_install:
  - gem update --remote bundler
  - gem update --system

sudo: false

bundler_args: --without=guard

notifications:
  disabled: true
